config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :comments
  resources :users
  post '/callback' => 'callback#callback'
  namespace :api, { format: 'json' }  do
    namespace :v1 do
      resources :comments
      resources :images
      get 'show_picture' => 'images#show_picture', :as => :show_picture
    end
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :image, ImagesUploader
end

app/controllers/api/v1/images_controller.rb
require 'net/http'
require 'uri'

module Api
  module V1
    class ImagesController < ApplicationBaseController
      before_action :set_image, only: [:show, :edit, :update, :destroy]
      def index
        @images = Image.all
      end

      def show
      end

      def show_picture
        redirect_to "/uploads/output.png"
      end

      def new
        @image = Image.new
      end

      def edit
      end

      def create
        @image = Image.new(image_params)
        respond_to do |format|
          if @image.save
            format.html { redirect_to @image, notice: 'Image was successfully created.' }
            format.json { render :show, status: :created, location: @image }
          else
            format.html { render :new }
            format.json { render json: @image.errors, status: :unprocessable_entity }
          end
        end
      end

      def update
        respond_to do |format|
          if @image.update(image_params)
            format.html { redirect_to @image, notice: 'Image was successfully updated.' }
            format.json { render :show, status: :ok, location: @image }
          else
            format.html { render :edit }
            format.json { render json: @image.errors, status: :unprocessable_entity }
          end
        end
      end

      def destroy
        @image.destroy
        respond_to do |format|
          format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      private
        def set_image
          @image = Image.find(params[:id])
        end

        def image_params
          params.require(:image).permit(:image)
        end
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  def index
    @images = Image.all
  end

  def show
  end

  def new
    @image = Image.new
  end

  def edit
  end

  def create
    @image = Image.new(image_params)
    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_image
      @image = Image.find(params[:id])
    end

    def image_params
      params.require(:image).permit(:image)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.image %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @image.image %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>